app/uk/gov/hmrc/integrationcataloguefrontend/controllers/UrlEncodingHelper.scala
test/uk/gov/hmrc/integrationcataloguefrontend/controllers/IntegrationControllerSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/controllers/UrlEncodingHelperSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/ListIntegrationsViewSpec.scala

API-4992 - Removed trailing hyphens from url

---

it/support/BaseISpec.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnectorSpec.scala

Co-authored-by: Anjum Abbas <anjumabbas5@users.noreply.github.com>

API-4990: Updated libraries and fixed tests

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailLayout.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/integrations/ListIntegrationsView.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/utils/ViewHelper.scala
test-common/uk/gov/hmrc/integrationcataloguefrontend/test/data/ApiTestData.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/ListIntegrationsViewSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailViewSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/utils/ViewHelperSpec.scala

the long description when larger than 180 characters

API-5006: added code to handle displaying short description when available. Also truncate ..

---

app/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnector.scala
app/uk/gov/hmrc/integrationcataloguefrontend/models/models.scala

API-5064 - Fixed spaces in hods filter names

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailLayout.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiEndpoints.scala.html
test/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailViewSpec.scala

API-5066 - Updated API details page

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html
test-common/uk/gov/hmrc/integrationcataloguefrontend/test/data/ApiTestData.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailViewSpec.scala

API-5066 - Does not show HoDs row if there is no data

---

app/uk/gov/hmrc/integrationcatalogue/models/ApiDetail.scala
app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html
test-common/uk/gov/hmrc/integrationcataloguefrontend/test/data/ApiTestData.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailViewSpec.scala

API-5063 - Added Status to ApiDetail

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html
test/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailViewSpec.scala

API-5079 - Update to DOM IDs for API Summary Page

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/technicaldetails/ApiTechnicalDetailsViewRedoc.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/technicaldetails/BareLayout.scala.html

API-5083 - Updated page titles for Api summary and details pages

---

app/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnector.scala
it/connectors/IntegrationCatalogueConnectorISpec.scala
it/controllers/IntegrationControllerISpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnectorSpec.scala

API-5093 - changed findWithFilters to only return APIs

---

app/uk/gov/hmrc/integrationcatalogue/models/ApiDetail.scala
test-common/uk/gov/hmrc/integrationcataloguefrontend/test/data/FileTransferTestData.scala

API-5091 - Added transports to FT model

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/NotFoundErrorTemplate.scala.html
it/controllers/IntegrationControllerISpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/NotFoundErrorTemplateSpec.scala

Fixed bug with space after <a> tags

API-5100: missed commit from last PR. 

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/about/About.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/homepage/HomePage.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/homepage/HomePageHeader.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/integrations/ListIntegrationsView.scala.html
test/uk/gov/hmrc/integrationcataloguefrontend/views/ListIntegrationsViewSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/homepage/HomePageHeaderSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/homepage/HomePageSpec.scala

- Home page 
- About page 
- Search APIs page

API-5140 - Content changes 

---

it/support/BaseISpec.scala
project/AppDependencies.scala
project/plugins.sbt

API-5124 - Play 2.8 Upgrade

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/includes/PlatformFilterComponent.scala.html
test/uk/gov/hmrc/integrationcataloguefrontend/views/includes/FilterApisComponentSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/views/includes/PlatformFilterComponentSpec.scala

API-5150 - Added DIGI and DAPI to Platform filters

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/casestudies/CaseStudies.scala.html

- Add 'no vistited' styleing to top anhor links
- Add 'back to top' links
- Remove 'We'll add more case studies later'

API-5111 - Case studie Tweaks

---

app/uk/gov/hmrc/integrationcatalogue/models/requestsAndResponses.scala
app/uk/gov/hmrc/integrationcataloguefrontend/services/IntegrationService.scala
it/connectors/IntegrationCatalogueConnectorISpec.scala
it/controllers/FileTransferControllerISpec.scala
it/controllers/IntegrationControllerISpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/controllers/FtWizardHelperSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/services/IntegrationServiceSpec.scala

contact information for a platform instead of using the oas contact information

Api 5263: added the abilty to read the platfrom override so we always use the platform

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailView.scala.html

API-5268 - Added govuk-body class to mailto link

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/apidetail/ApiDetailLayout.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/casestudies/CaseStudies.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/integrations/Layout3.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/integrations/ListIntegrationsView.scala.html
test/uk/gov/hmrc/integrationcataloguefrontend/views/ListIntegrationsViewSpec.scala

- Added contact email to Search APIs unhappy path
- Name of API corrected on Case Studies page

API-5285 - Content changes

---

app/uk/gov/hmrc/integrationcataloguefrontend/views/filetransfer/wizard/FileTransferWizardFoundConnections.scala.html
app/uk/gov/hmrc/integrationcataloguefrontend/views/integrations/ListIntegrationsView.scala.html

Nested `<p>` not allowed
`</br>` is not a valid tag

API-5448: Fix HTML parsing errors

---

app/uk/gov/hmrc/integrationcataloguefrontend/connectors/EmailConnector.scala
app/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnector.scala
app/uk/gov/hmrc/integrationcataloguefrontend/controllers/FileTransferController.scala
app/uk/gov/hmrc/integrationcataloguefrontend/controllers/IntegrationController.scala
build.sbt
it/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnectorISpec.scala
it/uk/gov/hmrc/integrationcataloguefrontend/support/EmailConnectorStub.scala
it/uk/gov/hmrc/integrationcataloguefrontend/support/MetricsTestSupport.scala
test/uk/gov/hmrc/integrationcataloguefrontend/connectors/IntegrationCatalogueConnectorSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/controllers/IntegrationControllerSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/controllers/QuickSearchControllerSpec.scala
test/uk/gov/hmrc/integrationcataloguefrontend/services/IntegrationServiceSpec.scala

* add missing case for contacting API team (but it would never happen)
* and intelliJ warnings of touched files

HIPP-660: fix all compiler warnings
